apiVersion: v1
kind: Service
metadata:
  name: reflexor-api
spec:
  selector:
    app.kubernetes.io/name: reflexor
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: 8000
