apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: reflexor-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reflexor
      app.kubernetes.io/component: api
